### ISSUE TITLE
Advanced filters?

### ISSUE THREAD

**Issue by thatsailorman** [recrm/ArchiveTools#3]
The warc extractor works like a charm on Windows when dumping all of the content...
I was wondering if you could provide some more info on the usage of filters?

For example... could we filter out sub-folders inside a warc archive based on folder name(s)? If so, how would I do that?

I also have a lot of index files in an archive, numbered like this: index.html, index(2).html, index(3).html etc. 
Would it be possible to only dump the first one in each folder (so, only the first index.html file) instead of all numbered index files as mentioned above?

Thanks in advance. :)

**Comment by recrm** [comment]
Sorry I don't think that is possible the way it is programmed. Right now it only uses substrings and it's been an age since I last worked on it. This was one of the projects I did while first learning the language so there are a lot of small optimizations like that that aren't in it. However, it shouldn't be that hard to edit. The check in question is inside the "checkfilter" function on line 678 and the exact boolean statement is on line 689. Shouldn't be to difficult to modify that line to accept regular expressions. Which would be able to do what you need. Or you could just dump all the files you need and just do a windows search and delete on any file that contains a bracket.

Actually, doing a filter on the substring "index.html" should work. As it isn't a substring of any of the ones with brackets. Possibly. I completely forget the warc header for filename, so I can't really give you the filter itself.
